name: Docker Image CI
on: [push]
  branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile
    - name: Publish to Docker Repository
      run: docker push dtahub/cicd
    with:
      name: dtahub/cicd
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}
